[package]
name = "dmarc"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7"
anyhow = "1"
tracing = "0.1"
mailparse = "0.14"
rustls-connector = "0.19"
tracing-subscriber = "0.3"
dmarc_aggregate_parser = "0.1"
imap = { version = "2", default-features = false }
clap = { version = "4", features = ["derive", "env"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
zip = { version = "0.6", default-features = false, features = ["deflate"] }
