[package]
name = "dmarc-report-viewer"
description = "Selfhosted standalone DMARC report viewer that fetches reports periodically from an IMAP mailbox"
keywords = ["dmarc", "email"]
categories = ["email"]
license = "MIT"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7"
anyhow = "1"
flate2 = "1"
futures = "0.3"
tracing = "0.1"
base64 = "0.22"
mailparse = "0.14"
serde-xml-rs = "0.6"
tokio-rustls = "0.25"
webpki-roots = "0.26"
tracing-subscriber = "0.3"
serde = {version = "1", features = ["derive"] }
clap = { version = "4", features = ["derive", "env"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread", "signal"] }
zip = { version = "0.6", default-features = false, features = ["deflate"] }
async-imap = {version = "0.9.7", default-features = false, features = ["runtime-tokio"] }
