[package]
name = "dmarc"
version = "0.1.0"
edition = "2021"

[dependencies]
imap = "2"
anyhow = "1"
native-tls = "0.2"
mailparse = "0.14"
dmarc_aggregate_parser = "0.1"
clap = { version = "4", features = ["derive", "env"] }
zip = { version = "0.6", default-features = false, features = ["deflate"] }
