[package]
name = "dmarc"
version = "0.1.0"
edition = "2021"

[dependencies]
imap = "2"
clap = { version = "4", features = ["derive", "env"] }
piz = "0.5"
anyhow = "1"
native-tls = "0.2"
mailparse = "0.14"
dmarc_aggregate_parser = "0.1"
